name: CI/CD for the ml-pipeline that builds all the pipeline modules and pushes them to the private PyPI registry. From where Airflow will install the latest versions and use them in the next run.

on:
  push:
    paths-ignore:
      - 'app-api/'
      - 'app-frontend/'
      - '**/*.yml'
      - '**/*.md'
    branches: [ "main" ]
    
env:
  INSTANCE_IP: '${{ vars.ML_PIPELINE_INSTANCE_IP }}'
  INSTANCE_USER: '${{ vars.INSTANCE_USER }}'

jobs:
  ci_cd:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'

      - name: 'SSH into EC2 instance and execute deployment script'
        uses: 'appleboy/ssh-action@master'
        with:
          host: ${{ env.INSTANCE_IP }}
          username: ${{ env.INSTANCE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ssh-keyscan -H ${{ env.INSTANCE_IP }} >> ~/.ssh/known_hosts
            ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ env.INSTANCE_USER }}@${{ env.INSTANCE_IP }} 'bash -s' << EOF
              cd ~/energy-forecasting
              git pull
              sh deploy/ml-pipeline.sh
            EOF
