name: CI/CD for the web app (API + frontend)

on:
  push:
    paths-ignore:
      - 'batch-prediction-pipeline/'
      - 'feature-pipeline/'
      - 'training-pipeline'
      - '**/*.yml'
      - '**/*.md'
    branches: [ "main" ]
    
env:
  AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
  AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
  INSTANCE_IP: '${{ secrets.INSTANCE_IP }}'
  INSTANCE_USER: '${{ secrets.INSTANCE_USER }}'

jobs:
  ci_cd:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'

      - name: 'Configure AWS credentials'
        run: |
          echo "[default]" >> $HOME/.aws/credentials
          echo "aws_access_key_id=${{ env.AWS_ACCESS_KEY_ID }}" >> $HOME/.aws/credentials
          echo "aws_secret_access_key=${{ env.AWS_SECRET_ACCESS_KEY }}" >> $HOME/.aws/credentials
          
      - name: 'SSH into EC2 instance and deploy the web app'
        uses: 'appleboy/ssh-action@master'
        with:
          host: ${{ env.INSTANCE_IP }}
          username: ${{ env.INSTANCE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/energy-forecasting
            git pull
            docker-compose -f deploy/app-docker-compose.yml --project-directory . up --build -d
