name: CI/CD for the ml-pipeline that builds all the pipeline modules and pushes them to the private PyPI registry. From where Airflow will install the latest versions and use them in the next run.

on:
  push:
    paths-ignore:
      - 'app-api/'
      - 'app-frontend/'
      - '**/*.yml'
      - '**/*.md'
    branches: [ "main" ]
    
env:
  INSTANCE_IP: '${{ vars.ML_PIPELINE_INSTANCE_IP }}'
  INSTANCE_USER: '${{ vars.INSTANCE_USER }}'

jobs:
  ci_cd:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'

      - name: 'SSH into EC2 instance and execute deployment script'
        uses: 'appleboy/ssh-action@master'
        with:
          HOSTNAME: ${{ env.INSTANCE_IP }}
          USER_NAME: ${{ env.INSTANCE_USER }}
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

          run: |
            echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              cd ~/energy-forecasting
              git pull
              sh deploy/ml-pipeline.sh
            EOF
