name: SSH into EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  ssh-into-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Create SSH Directory
        run: mkdir -p ~/.ssh

      - name: Copy .pem File
        run: cp C:\Users\Jia Sheng\aws\github.pem ~/.ssh/github.pem && chmod 600 ~/.ssh/github.pem
        
      - name: SSH into EC2 Instance
        env:
          INSTANCE_IP: '${{ vars.ML_PIPELINE_INSTANCE_IP }}'
          INSTANCE_USER: '${{ vars.INSTANCE_USER }}'
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/github.pem ${INSTANCE_USER}@${INSTANCE_IP} 'your_remote_command'
