name: SSH into EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  ssh-into-ec2:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SSH Client
        run: |
          choco install -y openssh

      - name: Create SSH Directory
        run: |
          mkdir C:\Users\runner\.ssh

      - name: Copy .pem File
        run: |
          Copy-Item -Path "C:\Users\Jia Sheng\aws\github.pem" -Destination "C:\Users\runner\.ssh\github.pem"
          icacls "C:\Users\runner\.ssh\github.pem" /inheritance:r
          icacls "C:\Users\runner\.ssh\github.pem" /grant:r "NT AUTHORITY\SYSTEM:(F)"
          icacls "C:\Users\runner\.ssh\github.pem" /grant:r "BUILTIN\Administrators:(F)"
          icacls "C:\Users\runner\.ssh\github.pem" /grant:r "BUILTIN\Users:(R)"
          icacls "C:\Users\runner\.ssh\github.pem" /grant:r "BUILTIN\Users:(F)"
          attrib +R "C:\Users\runner\.ssh\github.pem"

      - name: SSH into EC2 Instance
        env:
          INSTANCE_IP: '${{ vars.ML_PIPELINE_INSTANCE_IP }}'
          INSTANCE_USER: '${{ vars.INSTANCE_USER }}'
        run: |
          ssh -o StrictHostKeyChecking=no -i "C:\Users\runner\.ssh\github.pem" ${INSTANCE_USER}@${INSTANCE_IP} 'your_remote_command'
